title: <p align="center"> Vinoth K </p>
logo: /images/new.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/vinoth-k-84080b156">LinkedIn</a> |

  <a href="https://github.com/Vinoth029">GitHub</a>
 
  <br>  
  I'm having 2+ years of experience with Industrial automation and
  more than one year of experience with manufacturing domain. Currently I'm 
  pursuing PG program with upgrad on ML and AI.
  <br>
  </p>



theme: jekyll-theme-slate
